parent: base_df2d
image parameterization: pixels
clip guidance: 0
noise estimation: true
normalize_grads: false
use features: true
n_iterations: 500
accumulation: 1
guidance_scale: 10
guidance_change: 0
optimizer:
  learning rate: 0.03
  weight decay: 1e-6