parent: base_df2d
image parameterization: mlp
use features: false
augment: true
n_iterations: 500
guidance_change: -0.1
encoding:
  otype: Frequency
  n_frequencies: 7
network:
  otype: FullyFusedMLP
  activation: ReLU
  output_activation: None
  n_neurons: 128
  n_hidden_layers: 4
optimizer:
  learning rate: 5e-5
  weight decay: 1e-6