parent: base_df2d
image parameterization: instant-ngp
use features: false
accumulation: 1
augment: false
n_iterations: 500
init min frac: 0.2
init max frac: 0.8
step reduce frequency: 3
guidance_scale: 80
guidance_change: -0.1
fitting_iterations: 10000
# encoding:
#   otype: HashGrid
#   n_levels: 13
#   n_features_per_level: 2
#   log2_hashmap_size: 18
#   base_resolution: 16
#   per_level_scale: 1.33
encoding:
  otype: HashGrid
  n_levels: 6
  n_features_per_level: 2
  log2_hashmap_size: 14
  base_resolution: 16
  per_level_scale: 1.4
network:
  otype: FullyFusedMLP
  activation: ReLU
  output_activation: None
  n_neurons: 64
  n_hidden_layers: 1
optimizer:
  learning rate: 1e-4
  weight decay: 1e-5