parent: base_df
prompt: HDR photo, photorealistic, ultra hd, 30mm lens, wide angle
neg_prompt: ugly, blurry, grainy, cloudy
n_iterations: 300
guidance_scale: 25
depth_cutoff:
- 0.3
- 500
data:
  scene_id: des250
  type: 360
optimizer:
  learning rate: 1e-4
  weight decay: 1e-5