parent: base_df
prompt: HDR photo of an astronaut standing on a magnificent volcano, volcanic landscape, glorious sunset, hyper realistic, lava flow, 30mm lens, wide angle, extremely detailed 8k wallpaper, cinematic masterpiece
neg_prompt: ugly, blurry, cartoon
n_iterations: 300
guidance_scale: 100
guidance_decay: 0.98
depth_cutoff:
- 0.3
- 500
data:
  scene_id: desolation-partial
  type: 360
optimizer:
  learning rate: 5e-4
  weight decay: 1e-5