parent: base_df
prompt: HDR photo of a hiker standing on a mountain at sunrise, 30mm lens, wide angle
neg_prompt: ugly, blurry, cartoon, cloudy
n_iterations: 300
guidance_scale: 50
guidance_decay: 0.99
depth_cutoff:
- 0
- 500
data:
  scene_id: desolation-partial
  type: 360
optimizer:
  learning rate: 1e-4
  weight decay: 1e-5