parent: base_df
prompt: HDR photo of a giant tree, green forest landscape, ultra hd, extremely detailed 8k wallpaper, cinematic masterpiece
neg_prompt: ugly, blurry
n_iterations: 200
guidance_scale: 100
guidance_change: -0.1
step reduce frequency: 3
use features: true
backprop unet: false
depth_cutoff:
- 0
- 500
data:
  scene_id: desolation-partial
  type: 360
optimizer:
  learning rate: 1e-2
  weight decay: 0