parent: base_df
prompt: people on a rocky landscape, HDR photo, photorealistic, ultra hd, 30mm lens, wide angle
neg_prompt: ugly, blurry, grainy, cloudy, smooth
n_iterations: 300
guidance_scale: 75
guidance_change: -0.01
depth_cutoff:
- 0.3
- 500
condition on single view: true
data:
  scene_id: desolation-partial
  type: 360
  edited view: 11.png
optimizer:
  learning rate: 1e-4
  weight decay: 1e-5