data_nerfstudio_poster:
- a poster
- the floor
- a chair
data-nerfstudio-campanelle:
- the ground
- pasta
- a plate
- a table
data-nerfstudio-desolation:
- person
- the ground
- shoes
- a person's head